//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace Company.Language1
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class SoSa
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateSoSaMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Elements == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.Language1.Language1DomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"SoSa", "", "Elements"),
						"DSL0001", this);
			}
		} // ValidateSoSaMultiplicity
	} // class SoSa
} // Company.Language1

namespace Company.Language1
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class StructuralLayer
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateStructuralLayerMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.EnablingLayer == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.Language1.Language1DomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"StructuralLayer", this.Name, "EnablingLayer"),
						"DSL0001", this);
			}
		} // ValidateStructuralLayerMultiplicity
	} // class StructuralLayer
} // Company.Language1

namespace Company.Language1
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class EnablingLayer
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateEnablingLayerMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.LyfeCycleLayer == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.Language1.Language1DomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"EnablingLayer", "", "LyfeCycleLayer"),
						"DSL0001", this);
			}
		} // ValidateEnablingLayerMultiplicity
	} // class EnablingLayer
} // Company.Language1

namespace Company.Language1
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class LyfeCycleLayer
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateLyfeCycleLayerMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.SystemLayer == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.Language1.Language1DomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"LyfeCycleLayer", "", "SystemLayer"),
						"DSL0001", this);
			}
		} // ValidateLyfeCycleLayerMultiplicity
	} // class LyfeCycleLayer
} // Company.Language1

	
 