//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Language1
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "Language1";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Language1";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID Language1DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Language1CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID Language1ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Language1CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewLanguage1ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Language1CommandSetId), 0x0001);
	
		// Package identifier
		public const string Language1PackageId = "4fc57a9f-9b4b-43d6-97be-dfb236bae7d8";
		
		// Editor factory identifier
		public const string Language1EditorFactoryId = "f06c9bb9-811d-4e20-be9e-a8d4fee8fd51";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string Language1ModelExplorerToolWindowId = "20f06fc6-5590-42ac-abba-128b299750c9";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.Language1
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string Language1CommandSetId = "b44363d5-07cd-4d73-8a3f-6bbf5c3ed0e3";
	}
}